
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_CRYPTO_REQUEST = 'FETCH_CRYPTO_REQUEST';
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS';
export const FETCH_CRYPTO_FAILURE = 'FETCH_CRYPTO_FAILURE';

export const SET_CRYPTO1 = 'SET_CRYPTO1';
export const SET_CRYPTO2 = 'SET_CRYPTO2';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_COMPARISON_RESULT = 'SET_COMPARISON_RESULT';

export const SET_TIME_INTERVAL = 'SET_TIME_INTERVAL';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_CHART_TYPE = 'SET_CHART_TYPE';
export const FETCH_CHART_DATA_REQUEST = 'FETCH_CHART_DATA_REQUEST';
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
export const FETCH_CHART_DATA_FAILURE = 'FETCH_CHART_DATA_FAILURE';